### ISSUE TITLE
await connector.stop() cause infinite loop

### ISSUE THREAD

**Issue by olivialba** [sousa-andre/lcu-driver#38] opened 2023-10-21 15:12 UTC
When the client closes, 'await connector.stop()' causes an infinite loop, making the 'async def disconnect(_)' repeat infinitely. I am using the normal code example from the docs:

`from lcu_driver import Connector

connector = Connector()

@connector.ready
async def connect(connection):
    print('LCU API is ready to be used.')

@connector.close
async def disconnect(_):
    print('The client have been closed!')
    await connector.stop()

@connector.ws.register('/lol-summoner/v1/current-summoner', event_types=('UPDATE',))
async def icon_changed(connection, event):
    print(f'The summoner {event.data["displayName"]} was updated.')

connector.start()`

**Comment by Avnsx** [comment] 2023-10-21 15:14
Duplicate of: https://github.com/sousa-andre/lcu-driver/pull/34

**Comment by sousa-andre** [comment] 2023-12-20 21:28
Closing this as it is a duplicate. Thank you for pointing it out @Avnsx!

**Closed by sousa-andre** 2023-12-20 21:28 UTC
